In [2]:
import numpy as np


In [3]:
np1 = np.array([1,2,3,4])

In [4]:
np1

array([1, 2, 3, 4])

In [5]:
type(np1)


numpy.ndarray

In [7]:
mat1=np.array([[1,2],[3,4]])

In [8]:
mat1

array([[1, 2],
       [3, 4]])

In [9]:
type(mat1)


numpy.ndarray

In [10]:
np1.shape
mat1.shape

(2, 2)

In [11]:
np1.shape

(4,)

In [12]:
mat1[0,0]=5

In [13]:
mat1

array([[5, 2],
       [3, 4]])

In [15]:
mat2=np.arange(0,10,1)

In [16]:
mat3=np.linspace(0,10,20)

In [17]:
mat2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [12]:
import pandas as pd

In [1]:
import seaborn as sns

